import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from tkinter import END, BOTH, LEFT, RIGHT, X, Y, StringVar, IntVar, BooleanVar
import tkinter as tk
from tkinter import ttk, messagebox
try:
    import pygame
except ImportError:
    pygame = None
try:
    from PIL import Image, ImageTk
except ImportError:
    Image = ImageTk = None
try:
    import yt_dlp
except ImportError:
    yt_dlp = None
APP_DIR = Path(__file__).resolve().parents[2]
CACHE_DIR = APP_DIR / "cache"
AUDIO_CACHE_DIR = CACHE_DIR / "audio"
SETTINGS_FILE = APP_DIR / "settings.json"
APP_NAME = "Sonus"
_WINDOWS_ICON_HANDLES = []
LANGUAGES = {
    "en": {
        "search_placeholder": "Enter a track, artist, playlist or YouTube link…",
        "subtitle": "YouTube audio player",
        "process": "Process",
        "search_results": "Search results",
        "enter_query": "Enter a query or link.",
        "queue": "Queue",
        "queue_empty": "Queue is empty",
        "queue_hint": "Double-click — play. Ctrl+A — select all. Delete/Backspace — remove.",
        "now_playing": "Now playing",
        "preview": "Preview",
        "nothing_selected": "Nothing selected",
        "playback": "Playback",
        "mode": "Mode",
        "volume": "Volume",
        "add_to_queue": "Add to queue →",
        "normal": "Normal",
        "repeat_current": "Repeat current",
        "repeat_queue": "Repeat queue",
        "shuffle": "Shuffle",
        "ready": "Ready",
        "processing": "Processing…",
        "getting_data": "Getting data from YouTube…",
        "processing_error": "Processing error",
        "error": "Error",
        "nothing_found": "Nothing found.",
        "nothing_found_status": "Nothing found",
        "double_click_hint": "Double-click — add and play. “Add to queue →” — add without stopping the current track.",
        "found": "Found: {n}",
        "added_queue": "Added to queue: {n}",
        "link_added": "The link added {n} track(s) to the queue.",
        "search_first": "Search for something first",
        "track_added": "Track added to queue",
        "track_removed_play": "Track removed. Switching…",
        "removed_queue": "Removed from queue: {n}",
        "queue_cleared": "Queue cleared",
        "preparing_audio": "Preparing audio…",
        "queue_status": "In queue: {n} · Caching started",
        "playback_error": "Playback error",
        "playing": "Playing",
        "paused": "Paused",
        "pause_error": "Pause error: {e}",
        "resume_error": "Resume error: {e}",
        "seek_error": "Seek error: {e}",
        "queue_finished": "Queue finished",
        "preview_unavailable": "Preview unavailable",
        "dependency_missing": "Dependency not found",
        "unexpected_error": "An unexpected error occurred:\n\n{e}",
        "settings_title": "Settings",
        "settings_search_results": "Search results",
        "settings_search_desc": "Number of results for each new search. Choose from 1 to 50.",
        "results_label": "Results:",
        "cache_title": "Track caching",
        "cache_desc": "Background caching does not affect playback. When disabled, the current track is still cached when playback starts.",
        "cache_enable": "Cache tracks in the background",
        "download_mode": "Download mode",
        "streaming": "Streaming",
        "streaming_desc": "Download all tracks in order, from the first in the queue to the last.",
        "smart": "Smart",
        "smart_desc": "Download the currently selected track first, then all other tracks in queue order.",
        "mixed": "Mixed",
        "mixed_desc": "Download the current track first, then two previous and two next tracks; continue in queue order afterward.",
        "language": "Language",
        "language_desc": "Choose the language used by the Sonus interface.",
        "english": "English",
        "russian": "Русский",
        "close": "Close",
        "track_unavailable_status": "Track unavailable",
        "skip_unavailable": "Skipping unavailable track… Playing next…",
        "checking_track": "Checking track availability...",
        "settings_saved_mode": "Settings saved · {mode} caching",
        "settings_saved_off": "Settings saved · background caching disabled",
        "yt_missing": "yt-dlp is not installed. Run run_windows.bat or pip install -r requirements.txt",
        "pygame_missing": "pygame is not installed. Run run_windows.bat or pip install -r requirements.txt",
        "ffmpeg_missing": "ffmpeg was not found. It is required to prepare the OGG audio cache.",
        "no_title": "Untitled",
        "pause_playback": "Pause",
        "play_playback": "Play",
        "status_play": "Playback",
        "status_paused": "Paused",
        "status_resume": "Playback",
        "settings_error_title": "Settings",
        "default_language": "English",
        "legal_title": "Before you start",
        "legal_text": "Sonus is an independent desktop player intended for personal, non-commercial use.\n\nSonus does not host, store, or distribute YouTube media. Content is accessed at your request and may be temporarily cached on your device for playback and time-shifting.\n\nYou are responsible for complying with YouTube's Terms of Service, copyright law, and the rights of content creators. Use Sonus only with content you are permitted to access.",
        "legal_agree": "I agree",
        "legal_exit": "Exit",
    },
    "ru": {
        "search_placeholder": "Введите название трека, исполнителя, плейлист или ссылку YouTube…",
        "subtitle": "Аудиоплеер YouTube",
        "process": "Обработать",
        "search_results": "Результаты поиска",
        "enter_query": "Введите запрос или ссылку.",
        "queue": "Очередь",
        "queue_empty": "Очередь пуста",
        "queue_hint": "Двойной клик — воспроизвести. Ctrl+A — выбрать все. Delete/Backspace — удалить.",
        "now_playing": "Сейчас играет",
        "preview": "Превью",
        "nothing_selected": "Ничего не выбрано",
        "playback": "Управление воспроизведением",
        "mode": "Режим",
        "volume": "Громкость",
        "add_to_queue": "В очередь →",
        "normal": "Обычный",
        "repeat_current": "Повтор текущего",
        "repeat_queue": "Повтор очереди",
        "shuffle": "Случайный",
        "ready": "Готово",
        "processing": "Обрабатываю…",
        "getting_data": "Получение данных с YouTube…",
        "processing_error": "Ошибка обработки",
        "error": "Ошибка",
        "nothing_found": "Ничего не найдено.",
        "nothing_found_status": "Ничего не найдено",
        "double_click_hint": "Двойной клик — добавить и запустить. «В очередь →» — добавить без остановки текущего трека.",
        "found": "Найдено: {n}",
        "added_queue": "Добавлено в очередь: {n}",
        "link_added": "Ссылка добавила {n} трек(ов) в очередь.",
        "search_first": "Сначала выполните поиск",
        "track_added": "Трек добавлен в очередь",
        "track_removed_play": "Трек удалён. Переключение…",
        "removed_queue": "Удалено из очереди: {n}",
        "queue_cleared": "Очередь очищена",
        "preparing_audio": "Готовлю аудио…",
        "queue_status": "В очереди: {n} · Кэширование запущено",
        "playback_error": "Ошибка воспроизведения",
        "playing": "Воспроизведение",
        "paused": "Пауза",
        "pause_error": "Ошибка паузы: {e}",
        "resume_error": "Ошибка продолжения: {e}",
        "seek_error": "Перемотка: {e}",
        "queue_finished": "Очередь закончена",
        "preview_unavailable": "Превью недоступно",
        "dependency_missing": "Зависимость не найдена",
        "unexpected_error": "Произошла непредвиденная ошибка:\n\n{e}",
        "settings_title": "Настройки",
        "settings_search_results": "Результаты поиска",
        "settings_search_desc": "Количество результатов при каждом новом поиске. Можно выбрать от 1 до 50.",
        "results_label": "Результатов:",
        "cache_title": "Загрузка треков в кэш",
        "cache_desc": "Фоновая загрузка не влияет на воспроизведение. При отключении текущий трек всё равно будет загружен при запуске.",
        "cache_enable": "Загружать треки в кэш в фоне",
        "download_mode": "Режим загрузки",
        "streaming": "Потоковая",
        "streaming_desc": "Все треки скачиваются по порядку: от первого в очереди до последнего.",
        "smart": "Умная",
        "smart_desc": "Сначала загружается текущий выбранный трек, затем все остальные по порядку очереди.",
        "mixed": "Смешанная",
        "mixed_desc": "Сначала текущий трек, затем два предыдущих и два следующих; далее — остальные по порядку.",
        "language": "Язык",
        "language_desc": "Выберите язык интерфейса Sonus.",
        "english": "English",
        "russian": "Русский",
        "close": "Закрыть",
        "track_unavailable_status": "Трек недоступен",
        "skip_unavailable": "Пропускаю недоступный трек… Включаю следующий…",
        "checking_track": "Проверяю доступность трека...",
        "settings_saved_mode": "Настройки сохранены · {mode} загрузка",
        "settings_saved_off": "Настройки сохранены · фоновое кэширование отключено",
        "yt_missing": "Не установлен yt-dlp. Выполните run_windows.bat или pip install -r requirements.txt",
        "pygame_missing": "Не установлен pygame. Выполните run_windows.bat или pip install -r requirements.txt",
        "ffmpeg_missing": "Не найден ffmpeg. Он нужен для подготовки аудио-кэша OGG.",
        "no_title": "Без названия",
        "pause_playback": "Пауза",
        "play_playback": "Воспроизвести",
        "status_play": "Воспроизведение",
        "status_paused": "Пауза",
        "status_resume": "Воспроизведение",
        "settings_error_title": "Настройки",
        "default_language": "English",
        "legal_title": "Перед началом",
        "legal_text": "Sonus — независимый настольный проигрыватель для личного некоммерческого использования.\n\nSonus не размещает, не хранит и не распространяет медиаконтент YouTube. Контент запрашивается пользователем и может временно кэшироваться на вашем устройстве для воспроизведения и перемотки.\n\nВы несёте ответственность за соблюдение Условий использования YouTube, авторского права и прав создателей контента. Используйте Sonus только с контентом, к которому у вас есть право доступа.",
        "legal_agree": "Я согласен",
        "legal_exit": "Выйти",
    },
}
SEARCH_PLACEHOLDER = LANGUAGES["en"]["search_placeholder"]
THEMES = {
    "dark": {
        "name": "Тёмная",
        "bg": "#0e1118",
        "surface": "#151922",
        "surface_alt": "#1b202b",
        "surface_hover": "#22283a",
        "border": "#2b3140",
        "text": "#f4f5f8",
        "muted": "#8e96a8",
        "accent": "#9b6cff",
        "accent_hover": "#b089ff",
        "accent_text": "#ffffff",
        "select_bg": "#3b2a66",
        "select_text": "#ffffff",
        "placeholder": "#777f91",
        "danger": "#ef6262",
    },
}
YOUTUBE_URL_RE = re.compile(r"^(?:https?://)?(?:www\.)?(?:youtube\.com|youtu\.be)/", re.I)
